# Generated by Django 4.2.7 on 2025-02-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisteration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userregisteration',
            name='username',
        ),
        migrations.CreateModel(
            name='UserTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideSharingapp.userregisteration')),
            ],
        ),
    ]
