# Generated by Django 4.2.7 on 2025-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregisteration',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverregisteration',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderregisteration',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderregisteration',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
