# Generated by Django 4.2.7 on 2025-02-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharingapp', '0002_driverregisteration_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridetbl',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
